version: '3'
services:
  web:
    container_name: web
    build: ./microblog-web # SvelteKit アプリケーションのディレクトリ
    ports:
      - '5173:5173' # SvelteKit の開発サーバーのポート
    volumes:
      - ./microblog-web/:/app # 開発時のホットリロード用
      - node_modules:/app/node_modules # node_modulesをボリューム側に配置することにより速度改善
    depends_on:
      - backend # backend が起動するまで待つ
    environment:
      - PUBLIC_API_ORIGIN=http://localhost:3000 # API のオリジン
    command: bash -c "npm run dev"
    tty: true

  admin:
    container_name: admin
    build: ./admin # SvelteKit アプリケーションのディレクトリ
    ports:
      - '5174:5174' # SvelteKit の開発サーバーのポート
    volumes:
      - ./admin/:/app # 開発時のホットリロード用
      - node_modules_admin:/app/node_modules # node_modulesをボリューム側に配置することにより速度改善
    depends_on:
      - backend # backend が起動するまで待つ
    environment:
      - PUBLIC_API_ORIGIN=http://localhost:3000 # API のオリジン
    command: bash -c "npm run dev"
    tty: true

  backend:
    container_name: backend
    build: ./microblog-backend # Gin アプリケーションのディレクトリ
    ports:
      - '3000:3000' # Gin のサーバーのポート
    volumes:
      - ./microblog-backend/:/app
    depends_on:
      - mysql # MySQL が起動するまで待つ
      - redis # Redis が起動するまで待つ
    environment:
      - MYSQL_HOST=mysql # MySQL のホスト名
      - MYSQL_USER=user # MySQL のユーザー名
      - MYSQL_PASSWORD=password # MySQL のパスワード
      - MYSQL_DATABASE=mydatabase # MySQL のデータベース名
      - REDIS_HOST=redis # Redis のホスト名
      - REDIS_PORT=6379 # Redis のポート
      - REDIS_PASSWORD= # Redis のパスワード
      - REDIS_SECRET=secret # Redis のシークレットキー
      - APP_ORIGIN=http://localhost:5173 # アプリケーションのオリジン
      - ADMIN_ORIGIN=http://localhost:5174 # 管理画面のオリジン
    command: bash -c "go mod tidy && air"
    tty: true

  mysql:
    container_name: db
    image: mysql:latest
    ports:
      - '3306:3306' # MySQL のポート
    environment:
      - MYSQL_ROOT_PASSWORD=password # MySQL の root パスワード
      - MYSQL_DATABASE=mydatabase # MySQL のデータベース名
      - MYSQL_USER=user # MySQL のユーザー名
      - MYSQL_PASSWORD=password # MySQL のパスワード
    volumes:
      - mysql-data:/var/lib/mysql # データ永続化用

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379' # Redis のポート

volumes:
  node_modules: # node_modulesをボリューム側に配置することにより速度改善
  node_modules_admin: # node_modulesをボリューム側に配置することにより速度改善
  mysql-data: # DB永続化用
